### ISSUE TITLE
BackupEngine for iOS

### ISSUE THREAD

**Issue by iwasrobbed-ks** [iabudiab/ObjectiveRocks#16]
Hi there 👋 

I noticed that `RocksDBBackupEngine` is not included in the iOS source (only macOS). Is there a specific reason for this? 

Thanks!

Edit: Looks like RocksDB has `#ifndef ROCKSDB_LITE` in that class ☹️  Must be missing some support.

**Comment by iabudiab** [comment]
@rob-keepsafe Hey Rob 👋 

> Looks like RocksDB has #ifndef ROCKSDB_LITE in that class ☹️ Must be missing some support.

Exactly, that's the reason. Unfortunately many cool features of RocksDB are not included in the Lite version, e.g. TTL, encryption, transactions and **backups** 😿

**Comment by iwasrobbed-ks** [comment]
Womp womp, thanks all the same! 👍
