### ISSUE TITLE
terminating with uncaught exception of type std::length_error: vector

### ISSUE THREAD

**Issue by zhangxqq** [iabudiab/ObjectiveRocks#2]
create database, crash,"terminating with uncaught exception of type std::length_error: vector
"

**Comment by iabudiab** [comment]
@zhangxqq Hey there, could you please provide me more context. A snippet maybe? Or how are you creating the database?

**Comment by iabudiab** [comment]
@zhangxqq It seems that the issue is either fixed or abandoned. Feel free to reopen otherwise.
