### ISSUE TITLE
Support latest rocksdb version

### ISSUE THREAD

**Issue by zhangxqq** [iabudiab/ObjectiveRocks#3]
Will you support latest rocksdb version? I find rocksdb have updated for days.

**Comment by iabudiab** [comment]
@zhangxqq It is on my roadmap, however I cannot give you an exact ETA for the time being. I'll post an update as soon as possible.

**Comment by iabudiab** [comment]
@zhangxqq I've released `ObjectiveRocks v0.8.0` which wraps `rocksdb v5.4.6`.
The last release of `rocksdb` as of today is `5.5.2`. I'll try to update `ObjectiveRocks` accordingly in the next weekend.

**Comment by iwasrobbed-ks** [comment]
Update: https://github.com/iabudiab/ObjectiveRocks/commit/884b3b9bbbd2844a86d530e9be682e9256d16aa1 bumped this to `v5.11.3` which was released on March 12. 

The current rocksdb release is `v5.13.1` as of 9 days ago.

**Comment by iabudiab** [comment]
@rob-keepsafe Looks like a _"thinko"_ on my part there 💩

I'll update to `5.13.1` after merging PR #9 which also may serve as a sanity check/test run for future updates to the Pod 👍

**Comment by iwasrobbed-ks** [comment]
@iabudiab It should be as easy as just bumping the submodule like you've been doing and then just cutting a new tag. Then you'd update the podspec's version to match your tag and push it up

**Comment by iabudiab** [comment]
Updated to `5.13.1` in 5ddaeb20ca8b84ad00f0c20eb37f0e5f0e4946e1
