### ISSUE TITLE
Add support to arm64 architecture

### ISSUE THREAD

**Issue by rogerluan** [iabudiab/ObjectiveRocks#30]
Hey 👋 

I've encountered an issue while trying to compile an app that uses ObjectiveRocks as a dependency to be run on a arm64 simulator. I wonder if there're any plans to add support to arm64 architecture, and if there's anything I can do to help achieve that?

This is the error I get when attempting to compile for arm64 simulator on an M1 computer running Xcode on Rosetta:

```
❌  ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/redacted/Pods/ObjectiveRocksFramework/iOS/ObjectiveRocks.framework/ObjectiveRocks' for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **
```

Appreciate any help!

**Comment by iabudiab** [comment]
Hey @rogerluan 👋 

I'll look into that and report here 😉 
Maybe on the next weekend

**Comment by rogerluan** [comment]
Appreciate it @iabudiab ! 🙏

**Comment by rogerluan** [comment]
This issue can be closed. If anyone ends up in this thread, check out: https://developer.apple.com/forums/thread/655768
